### ISSUE TITLE
Support Servlet API v6

### ISSUE THREAD

**Issue by globalworming** [googleapis/java-logging-servlet-initializer#283]
there is an incomplete PR #161  
please finish that :)

**Comment by losalex** [comment]
@globalworming, as I mentioned in [284](https://github.com/googleapis/java-logging-servlet-initializer/pull/284), the version for `jakarta.servlet` was chosen to support wider audience of developers which could benefit from this package. We are keeping PR [161](https://github.com/googleapis/java-logging-servlet-initializer/pull/161) open simply to prevent future updates to this library for `jakarta.servlet` since updates performed automatically. I am closing this issue for now - feel free to reactivate if you think we should still commit this change
